### ISSUE TITLE
Memory Error - Pennsylvania

### ISSUE THREAD

**Issue by bowlesgsrcx** [germrothdaniel/MicrosoftBuildingsToFeatureclass#1]
Thanks for the script. I got a memory error while running the script on the Pennsylvania data. Any suggestions?
Thanks,
--gary

**Comment by dlatto24** [comment]
Just got a memory error for Illinois as well: 

Executing: JsonToFC F:\GIS\Illinois\Illinois\Illinois.geojson "PROJCS['NAD_1983_StatePlane_Illinois_East_FIPS_1201_Feet',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',984250.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-88.33333333333333],PARAMETER['Scale_Factor',0.999975],PARAMETER['Latitude_Of_Origin',36.66666666666666],UNIT['Foot_US',0.3048006096012192]];-17463800 -46132600 3048.00609601219;-100000 10000;-100000 10000;3.28083333333333E-03;0.001;0.001;IsHighPrecision" F:\GIS\US_Data\MicrosoftBuildingsToFeatureclass-master\Json_to_Featureclass\Json_to_Featureclass\BuildingFootprints.gdb BuildingFootprints_Illinois
Start Time: Fri Oct 12 12:37:36 2018
Running script JsonToFC...
Script executed at 2018-10-12 12:37:36
Creating empty featureClass at given location
Failed script JsonToFC...

Traceback (most recent call last):
  File "F:\GIS\US_Data\MicrosoftBuildingsToFeatureclass-master\Json_to_Featureclass\Json_to_Featureclass\GeoJSON_toFC.py", line 55, in <module>
    json_raw_dataDict = json.load(infile)
  File "C:\Python27\ArcGIS10.5\Lib\json\__init__.py", line 291, in load
    **kw)
  File "C:\Python27\ArcGIS10.5\Lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\ArcGIS10.5\Lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\ArcGIS10.5\Lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
MemoryError

Failed to execute (JsonToFC).
Failed at Fri Oct 12 12:38:05 2018 (Elapsed Time: 29.07 seconds)

**Comment by tulip1992** [comment]
Hi, thanks for the script! I ran into the same memory error with Pennsylvania. Is there a workaround? I'd love to just pull out the geographic area I want, as opposed to processing the whole state, if that would help with the memory error. 

Executing: JsonToFC C:\Users\xxx\Desktop\Footprints\Pennsylvania.geojson "PROJCS['NAD_1983_StatePlane_Pennsylvania_South_FIPS_3702_Feet',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Lambert_Conformal_Conic'],PARAMETER['False_Easting',1968500.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-77.75],PARAMETER['Standard_Parallel_1',39.93333333333333],PARAMETER['Standard_Parallel_2',40.96666666666667],PARAMETER['Latitude_Of_Origin',39.33333333333334],UNIT['Foot_US',0.3048006096012192]];-119214200 -96198500 3048.00609601219;-100000 10000;-100000 10000;3.28083333333333E-03;0.001;0.001;IsHighPrecision" C:\Users\mpeterson\Desktop\Footprints\Footprints.gdb Footprints_PA
Start Time: Fri Oct 12 13:11:43 2018
Running script JsonToFC...
Script executed at 2018-10-12 13:11:43
Creating empty featureClass at given location
Failed script JsonToFC...

Traceback (most recent call last):
  File "C:\Users\xxx\Desktop\Footprints\GeoJSON_toFC.py", line 55, in <module>
    json_raw_dataDict = json.load(infile)
  File "C:\Python27\ArcGIS10.4\Lib\json\__init__.py", line 290, in load
    **kw)
  File "C:\Python27\ArcGIS10.4\Lib\json\__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\ArcGIS10.4\Lib\json\decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\ArcGIS10.4\Lib\json\decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
MemoryError

Failed to execute (JsonToFC).
Failed at Fri Oct 12 13:12:05 2018 (Elapsed Time: 21.79 seconds)
